updated to version 4.1+Debian11ubuntu6.2

diff --git a/init-functions.d/01-upstart-lsb b/init-functions.d/01-upstart-lsb
--- a/init-functions.d/01-upstart-lsb
+++ b/init-functions.d/01-upstart-lsb
@@ -18,9 +18,23 @@ if [ -r "/etc/init/${_UPSTART_JOB}.conf" ] && which initctl >/dev/null \
 then
    # Upstart configuration exists for this job and we're running under upstart
    case "${1:-}" in
-      start|stop|status|reload)
+      start|stop|reload)
          # Action is a valid upstart action
          exec ${1} ${_UPSTART_JOB}
+      ;;
+      status)
+         # return code of the command only tells us upstart is running, not
+         # the status of the job.  Map to LSB values.
+         output=$(${1} ${_UPSTART_JOB}) || exit 4
+         echo "$output"
+         case $output in
+            *start/running*)
+                exit 0 ;;
+            *stop/waiting*)
+                exit 3 ;;
+            *)
+                exit 4 ;;
+         esac
       ;;
       restart|force-reload)
         # Map restart to the usual sysvinit behavior.
